apiVersion: apps/v1
kind: Deployment
metadata:
  name: exfilterui
  labels:
    app: exfilterui
spec:
#	replicas: 2
  selector:
    matchLabels:
      app: exfilterui
  template:
    metadata:
      labels:
        app: exfilterui
    spec:
      containers:
        - image: alexchan20/exfilterui:latest
          name: exfilterui
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: exfilterui
  labels:
    app: exfilterui
spec:
  type: NodePort
  selector:
    app: exfilterui
  ports:
    - port: 8000
      targetPort: 8000